### ISSUE TITLE
Integrate this in my website

### ISSUE THREAD

**Issue by abhinav76** [gauntface/simple-push-demo#10]
how would i integrate the code to enable notifications on my website? I downloaded the code but when i change gcm_sender_id and api_key from files, it doesn't work.
Do I have to change PUSH_SERVER_URL in main.js? @gauntface

**Comment by gauntface** [comment]
I'd recommend going through this blog post which walks through setting and using everything: https://developers.google.com/web/updates/2015/03/push-notificatons-on-the-open-web

If you wanted to host your own copy of this demo then yes you would need to change the push server url, although the server side of this isn't built for production, only to serve as the most basic of demo's.
