### ISSUE TITLE
Push notification sent to Monitor#1 instead of currently active browser

### ISSUE THREAD

**Issue by nolaandy** [gauntface/simple-push-demo#101]
FYI, if I'm surfing using Monitor #2 and you want a push notification to execute after some user action on the website, the notification can go lost, especially if your setup is [Monitor2] | [Monitor1]

**Comment by gauntface** [comment]
Sadly that is out of the control of the developer. The browser determines a lot of aspects of the notification. Probably best to raise this as a bug on the browser you are using.
