### ISSUE TITLE
Not working on Firefox mac osx but works on firefox windows.

### ISSUE THREAD

**Issue by neelgo** [gauntface/simple-push-demo#114]
Hosted the demo here: https://gothania.com/simple-push/src/

It works without issue on firefox v 48.0.2 windows 7
but not on firefox 48.0.2 on mac osx 10.11.6
also not on safari 9.1.3 on mac osx 10.11.6

**Comment by gauntface** [comment]
What is the problem? "doesn't work" is hard to be helpful with.

Firefox did go through a period of being broken not long ago , so it could simply be that

**Comment by gauntface** [comment]
Just run the tests which include integration tests with browsers and everything seems fine. Please reopen with more information if you are still hitting these issues.

**Comment by neelgo** [comment]
Hi Matthew,

Did you get a chance to look at url https://gothania.com/simple-push/src/ ?
When I load this in mac on firefox. the toggle button is disabled.
but not on windows firefox.
