### ISSUE TITLE
No CURL command available

### ISSUE THREAD

**Issue by DavidScales** [gauntface/simple-push-demo#119]
<img width="767" alt="screen shot 2016-10-06 at 5 46 50 pm" src="https://cloud.githubusercontent.com/assets/16726377/19175645/6aa9b2e6-8bed-11e6-92d7-36fc44e125f4.png">
When adding payload text, the demo produces this warning

*Sorry, but because the web push protocol requires a stream as the body of the request, there is no CURL command that will stream an encrypted payload.*

rather than a CURL command.

**Comment by gauntface** [comment]
What would make the error message more clear?

**Comment by DavidScales** [comment]
Maybe if you gave me better reading skills? Sorry I jumped the gun on that.
