### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by eschmid72** [gauntface/simple-push-demo#13]
Tested with node.js 0.12.9:

* `npm`-warnings:
```
npm WARN package.json Dependency 'express' exists in both dependencies and devDependencies, using 'express@^4.13.3' from dependencies
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.
npm WARN deprecated gulp-minify-html@1.0.5: Consider using gulp-htmlmin instead
npm WARN peerDependencies The peer dependency continuation-local-storage@~3 included from cls-bluebird will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN optional dep failed, continuing fsevents@1.0.6
```
* `gulp serve`:

`Task 'serve' is not in your gulpfile`
-> should be `node app`

* in `app.js` line 11:

`SyntaxError: Use of const in strict mode`

**Comment by ashishtilara** [comment]
+1

**Comment by gauntface** [comment]
The peerDepenecies are bad - sorry, but it doesn't stop it from running.

The const error in strict mode - I've got use strict in the repo at the moment, but it could be an issue with 0.12 of node, I'm on 4.2 - the latest stable version of node.

**Comment by gauntface** [comment]
Had a huge tidy up so this shouldn't be a problem anymore and moving forward the David badges should help highlight when things get out of date.
