### ISSUE TITLE
Doesn't work on Chrome 53?

### ISSUE THREAD

**Issue by jmduke** [gauntface/simple-push-demo#138]
Enabling notifications correctly gets the prompt from chrome, but nothing happens thereafter:

![screenshot 2016-10-18 22 30 59](https://cloud.githubusercontent.com/assets/461046/19506704/9e3cbc0e-9582-11e6-80d3-489eea888ebf.png)

(Thanks for your work on this demo! Navigating the web push API has been a big pain point for me and I appreciate this resource a lot.)

**Comment by jmduke** [comment]
Actually, scratch that -- I tried on my partner's Sierra laptop w/ Chrome 53 and it worked fine.  Can you think of anything that might cause this behavior?

**Comment by jmduke** [comment]
(No console output, either.)

**Comment by gauntface** [comment]
This is a bug in Chrome a few people have been hitting :(

It's down to an issue with a database getting corrupted and Chrome getting into a bad state: https://bugs.chromium.org/p/chromium/issues/detail?id=623062#c37
