### ISSUE TITLE
Sending Data in Curl Request

### ISSUE THREAD

**Issue by ashishtilara** [gauntface/simple-push-demo#14]
Is there anyway we can send data with registration_ids, such as message + title? How do I read it in serviceworker.js

I've noticed https://developer.mozilla.org/en-US/docs/Web/API/PushEvent but don't seem to work in Chrome.

Appreciate any guidance.

**Comment by gauntface** [comment]
The data support is coming, but it needs to be encrypted.

Firefox and Chrome latest versions have got support for this, but it requires you to encrypt payload. There is a sample of this in the repo (added fairly recently) but it's only tested in Chrome and I'm expecting it to break / change soon so I'd say feel free to play with it, but expect breaking changes.
