### ISSUE TITLE
Not working on chrome and safari browsers running on macOs

### ISSUE THREAD

**Issue by larsespen9** [gauntface/simple-push-demo#145]
I have tested the simple-push-demo on chrome, safari and firefox. 
Firefox is the only browser that works for me. Is there some tweaks that needs to be 
implemented?

**Comment by Format-X22** [comment]
chrome://flags/#enable-native-notifications

**Comment by gauntface** [comment]
Safari doesn't support web push so it won't work there.

What version of Chrome are you using? What happens when you try it?

**Comment by larsespen9** [comment]
I am using Chrome version 54.0.2840.98 (64-bit). The page loads but no token is obtained.  https://www.youtube.com/watch?v=b-JZQyWi-YU

**Comment by gauntface** [comment]
This is a bug in Chrome a few people have been hitting :(

It's down to an issue with a database getting corrupted and Chrome getting into a bad state: https://bugs.chromium.org/p/chromium/issues/detail?id=623062#c37

This is fixed Chrome version 55 (Chrome beta.

**Comment by larsespen9** [comment]
Thank you for the respons. I have tested the latest chrome beta version and this solved the problem  I had: retrieving the Instance ID Token.
