### ISSUE TITLE
Unable to see notification on Mobile Chrome v55.0.2883.91 (Android)

### ISSUE THREAD

**Issue by jonwhittlestone** [gauntface/simple-push-demo#151]
Hi

When I visit https://gauntface.github.io/simple-push-demo/
I click slider for _Enable Push Notifications_
I enter text 'Test' in field _Add Payload Text_
I click _SEND A PUSH VIA XHR_

**What I expect to Happen**
I see an Android notification 'Test' in the taskbar

**What actually happened**
I saw a Chrome dialog asking me to add guantface.github.io to the homescreen
After accepting to add to the homescreen, subsequent clicking of _SEND A PUSH VIA XHR_ did not give a Android notification

**Environment**

Android 7.0
Nexus 6

**Additional notes**

I also tried the above scenario on a Samsung S6 running Android 6.0.1 and had the same outcome.

Thanks

**Comment by gauntface** [comment]
I just tried this on Chrome Stable (version 55) and it's working.

What version of Chrome are you testing on? (Menu -> Settings -> About Chrome)

**Comment by jonwhittlestone** [comment]
Hi

as per title

![screenshot_20170104-164247](https://cloud.githubusercontent.com/assets/1681212/21650534/20529e46-d29d-11e6-9e3b-990ec16469f2.png)

**Comment by jonwhittlestone** [comment]
Thanks, I got this working using the Android emulator, SDK 24

This can be closed.

Additional questions though:

* If the device is locked, will new notifications arrive / be shown?
* If the Chrome browser is running in the background, will notifications arrive / be shown in the taskbar?

Thanks for your work on this

**Comment by RichardMaher** [comment]
.

**Comment by gauntface** [comment]
In response to your questions - yes and yes.

Only caveat is that android settings still affect the notifications (i.e. if the user says not to display notifications on the lockscreen, chrome notifications will adhere to this and no show on the lockscreen).
