### ISSUE TITLE
Offline Label

### ISSUE THREAD

**Issue by NistorCristian** [gauntface/simple-push-demo#158]
Hi, this is not an issue but a question. I checked multiple pwa and yours is the only one that has that label on Android. I looked into your code but I didn't find something related to this.

Any suggestions?

![60f1721f4eae2550ea3b3e0fddaee812ffdf2b0ed06e7ab730 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/12628663/23069206/3a5c3450-f52f-11e6-85f3-4621835825d0.jpg)

**Comment by gauntface** [comment]
Interesting. What browser and version are you using?

**Comment by NistorCristian** [comment]
Android 6.0.1 Chrome. v55.0.2883.91

**Comment by gauntface** [comment]
Just spoke to a colleague and it's offline when you bookmark the URL by the looks of it (I've never used this feature).

https://medium.com/totally-tooling-tears/issue-4-offline-badging-testing-travis-devtools-issues-web-storage-data-driven-development-8dd1cfbc410a#.q3j14t6dj
