### ISSUE TITLE
'permissions' in navigator check fails in Firefox 44

### ISSUE THREAD

**Issue by edmoz** [gauntface/simple-push-demo#16]
Hi, 
https://github.com/gauntface/simple-push-demo/blob/master/app/scripts/push-client.es6.js#L71
checks for `'permissions' in navigator `. This isn't supported in Fx44 which we launched Push support. Can you change it to: `'permission' in Notification` . I might be able to do a PR shortly

**Comment by gauntface** [comment]
Thanks for the heads up on this.

Will take a look. I think I've only really been testing on Firefox Nightly (which I'm guessing is newer than 44).

**Comment by quicoto** [comment]
+1 for this, otherwise it just works on Chrome. Would love to test it on FF 44 stable.

**Comment by marco-c** [comment]
The problem should apply to Firefox 45 as well.

**Comment by gauntface** [comment]
Just switched to Notification.permission due to issues with the permissions API in FF.
