### ISSUE TITLE
UnauthorizedRegistration error 400

### ISSUE THREAD

**Issue by ofirk11** [gauntface/simple-push-demo#169]
Hello 
3 days i work to fiend problem ,and i use this script to save users only and 
https://github.com/web-push-libs/web-push-csharp
to send message.

i saw that all the pepole that register from this script with ID that start with fcm i can send the notification but all the pepole that start with android (gcm ) i am get the error  on the title .

also i am fiend code that work fine with gcm (android ) but it make only gcm ID this is the code:

 i am add link also to manifest.json
<script type="text/javascript">
function base64UrlToUint8Array(base64UrlData) {
  const padding = '='.repeat((4 - base64UrlData.length % 4) % 4);
  const base64 = (base64UrlData + padding)
    .replace(/\-/g, '+')
    .replace(/_/g, '/');
  const rawData = atob(base64);
  const buffer = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    buffer[i] = rawData.charCodeAt(i);
  }
  return buffer;
}

(function() {
  if (!('serviceWorker' in navigator)) {
    return;
  }

  return navigator.serviceWorker.register('service-worker.js')
  .then(function(registration) {
    console.log('service worker registered');
    return navigator.serviceWorker.ready;
  })
  .then(function(reg) {
    var channel = new MessageChannel();
    channel.port1.onmessage = function(e) {
      window.document.title = e.data;
    }
    reg.active.postMessage('setup', [channel.port2]);

    var subscribeOptions = { userVisibleOnly: true };
    // Figure out the vapid key
    var searchParam = window.location.search;
    vapidRegex = searchParam.match(/vapid=(.[^&]*)/);
    if (vapidRegex) {
      // Convert the base 64 encoded string
      subscribeOptions.applicationServerKey = base64UrlToUint8Array(vapidRegex[1]);
    }

    console.log(subscribeOptions);

    return reg.pushManager.subscribe(subscribeOptions);
  })
  .then(function(subscription) {
    console.log(JSON.stringify(subscription));
    window.subscribeSuccess = true;
    window.testSubscription = JSON.stringify(subscription);
  })
  .catch(function(err) {
    window.subscribeSuccess = false;
    window.subscribeError = err;
  });
})();
</script>

how we can do that the problem will be fixed, this is link to stackoverflow that i open to more info 
http://stackoverflow.com/questions/44042472/web-push-unauthorizedregistration-error-400

**Comment by gauntface** [comment]
For future reference, please put more time into formatting your issues. Markdown is weird at first, but both stackoverflow and github give you some nice editing tools, so please take the time to learn how to style code and keep indentation.

Please see stackoverflow for answers to this.
