### ISSUE TITLE
Missing Javascript And Style Files

### ISSUE THREAD

**Issue by Amr-alshroof** [gauntface/simple-push-demo#17]
i got an error (404 does not exist) on fetching the main.js and main.css  files which are used in the index.html view.

**Comment by oldergod** [comment]
Did you run the `gulp serve` command as explained in the README ?

**Comment by gauntface** [comment]
As @oldergod pointed out, you need to run the `gulp dev` command to run the local server with converting of JS ES2015 - ES5 and Sass to CSS.
