### ISSUE TITLE
Push event of service worker is not being called in multiple tabs

### ISSUE THREAD

**Issue by MathikumarC** [gauntface/simple-push-demo#173]
I am using Web Push protocol to send push notifications. I have registered a service worker and subscribed successfully with pushManager in one tab. When I send messages push event able to receive notification and logs the messages in console.

I am opening the same url and same service worker is getting registered and returning same subscription using below snippet.

serviceWorkerRegistration.pushManager.getSubscription()

But when I send messages, first tab only logs the messages in console. second tab is not logs the messages in console.

When I close the first tab and send messages, now I am able see the messages in second tab console logged by service worker.

Note: Both the tabs loaded in same origin. Example: https://localhost:8080/WebPush

Below is my service worker code

    self.addEventListener('push', function(event) {
      if (event.data) {
         console.log('This push event has data: ', event.data.text());
      } 
      else {
         console.log('This push event has no data.');
      }
   });
At the same time when I try using firebase , I am able receive messages in both the tabs.

Can you help me out to receive messages on both the tabs using web push.

I have raised this case in stackoverflow also. Please let me know the possibilities to achieve this.

Thanks in advance.

**Comment by MathikumarC** [comment]
After some research , I have find out an one possible way to achieve this use case.

After push event triggered, using service worker clients API, I will find out number of open clients in the same origin and post message to all the clients.

Below is the code snippet need to add inside push event in the service worker.

    clients.matchAll({
        type: 'window',
        includeUncontrolled: true
      })
      .then(function(windowClients)
      {   
        windowClients.forEach(function(windowClient){
        windowClient.postMessage({
          message: 'Received a push message.'+event.data.text(),
          time: new Date().toString()
        });
      });

});
And add a service worker listener.

    navigator.serviceWorker.addEventListener('message', function(event) {
      console.log('Received a message from service worker: ', event.data);
    });

**Comment by gauntface** [comment]
This is the wrong repo for this kind of question, but I did write up some info here: https://web-push-book.gauntface.com/chapter-05/04-common-notification-patterns/#message-a-page-from-a-push-event
