### ISSUE TITLE
Unable to get demo app to work on my site

### ISSUE THREAD

**Issue by johanvena** [gauntface/simple-push-demo#18]
I have downloaded zip file and extracted it on my website in a test folder Found following reference file name errors and corrected the file names in the folder

main.es6.js   ===must be===> main.js
encryption-test.scss   ===must be===> encryption-test.css
main.scss   ===must be===> main.css

The enable push notification slider is not active unable to slide

Did change my API Key and project Id but can't get it working

Don't know if I am missing something, can you help my demo url is

https://4u2shop.co.za/test/test6/

Thanx
Johan

**Comment by oldergod** [comment]
Those transformation are done by `gulp` in this project. You either need a similar process to transpile `es6` and transform `scss` to `css` files.

See: https://github.com/gauntface/simple-push-demo/blob/master/gulpfile.js and https://github.com/gauntface/simple-push-demo/tree/master/gulp-tasks

**Comment by gauntface** [comment]
Thanks @oldergod for the comments.

I've gone through and changed the code a little today, but checkout the gulp file and gulp-tasks for how I do the transpilation. 

You should *hopefully* be able to fork this repo and publish your changes to gh-pages without too much hassle.
