### ISSUE TITLE
Not working with Node 10 ?

### ISSUE THREAD

**Issue by bbsimonbb** [gauntface/simple-push-demo#198]
I'm a gulp newbie, but I would be interested in taking this project for a spin. Unfortunately, the project is built with Gulp 3.9, which is not compatible with Node 10. Gulp 4.0 requires a pretty thorough rewrite, it seems, of all gulp files, and dropping back to Node 8 seems to me a drastic option. If these things are considered too hard (they're too hard for me) this project should sadly be considered broken. No fault of your own :-|

**Comment by gauntface** [comment]
Sorry for the complete lack of response (I've only just started getting GitHub notifications to work for my workflow).

I've moved away from gulp completely and this project now only needs a simple http server, you can use python server or just run `npm install && npm run dev` and it should work.

The README has this info now.

Please feel free to re-open if you see this and run into issues.
