### ISSUE TITLE
Deployed version doesn't waitUntil showNotification resolves

### ISSUE THREAD

**Issue by johnmellor** [gauntface/simple-push-demo#20]
The deployed version of https://simple-push-demo.appspot.com/service-worker.js triggers the dreaded "This site has been updated in the background." warning notification.

That's because it doesn't `waitUntil` `registration.showNotification` resolves. Specifically it has the following minified source code (prettified by DevTools):

```js
function showNotification(t, e, o, i) {
    var n = {
        body: e,
        icon: o ? o : "images/touch/chrome-touch-icon-192x192.png",
        tag: "simple-push-demo-notification",
        data: i
    };
    self.registration.showNotification(t, n)
}
```

The last line should be `return self.registration.showNotification(t, n)`. I notice this is fine in https://github.com/gauntface/simple-push-demo/blob/master/app/service-worker.js, so it seems either:
a) the site just needs to be redeployed; or
b) the minifier is breaking this.

**Comment by gauntface** [comment]
Argh - my bad.

I've simplified the sw code - going to add some tests tomorrow.
