### ISSUE TITLE
don't work in firefox

### ISSUE THREAD

**Issue by jimmywarting** [gauntface/simple-push-demo#203]
Hi, i guess Firefox is using `aes128gcm` but your factory thinks it only supports `aesgcm`
`PushManager.supportedContentEncodings` isn't available in FF - so therefor supported encodings thinks it `[aesgcm]` - which is wrong?

I notice that if i changed
```diff
- let supportedContentEncodings = ['aesgcm'];
+ let supportedContentEncodings = ['aes128gcm'];
```
Then it will work

The relevant part of it all:
https://github.com/gauntface/simple-push-demo/blob/3b55ad9aa10800713fb37d59a425fd7e86f9def7/src/scripts/encryption/encryption-factory.js#L12-L21

**Comment by gauntface** [comment]
Looks like Firefox doesn't defined the `supportedContentEncodings` and looking at the spec, the requirement is that they must support aes128gcm.

```
[User agents](https://w3c.github.io/push-api/#dfn-user-agent) MUST support the aes128gcm content coding defined in [[RFC8291](https://w3c.github.io/push-api/#bib-rfc8291)], and MAY support content codings defined in previous versions of the draft for compatibility reasons.
```

https://w3c.github.io/push-api/#dom-pushmanager-supportedcontentencodings
