### ISSUE TITLE
navigator.permissions.query({name: 'push', userVisibleOnly: true}) fails in Firefox Nightly

### ISSUE THREAD

**Issue by marco-c** [gauntface/simple-push-demo#22]
`https://github.com/gauntface/simple-push-demo/blob/c59520bd82f2ff6c673869b03cc266f83dd9b0a2/app/scripts/push-client.es6.js#L107`

**Comment by gauntface** [comment]
Looked into this - it looks like nightly just throws an error along the lines of 'not implemented yet'. I've changed it to just use Notification.permission in latest changes.
