### ISSUE TITLE
Allow user to set the payload manually for supporting browser

### ISSUE THREAD

**Issue by oldergod** [gauntface/simple-push-demo#26]
Would you be open to it? I would be happy to do it.

**Comment by gauntface** [comment]
I was planning on doing this using the web encryption API so it can be hosted in the browser, happy to take a PR if you want to have a crack at it :)

**Comment by oldergod** [comment]
I was thinking about only adding the `keys` and `auth` properties to the notification.
Are you talking about moving/merging the server―`app.js`―to the client? If so, I might not have enough time.
I'll play around on my fork and create a PR if I come up with anything then.

**Comment by gauntface** [comment]
The encryption stuff at the moment is relying on a server that I'd rather not have to maintain at the moment so I'm intending on moving that over to using the encryption API - probably reusing @beverloo's handy work here: https://github.com/beverloo/peter.sh/blob/master/tests/cases/webcrypto-push-encryption.js

**Comment by gauntface** [comment]
@oldergod  Just pushed an update that adds encrypted payload support. let me know if there is anything else you had in mind.

**Comment by oldergod** [comment]
Perfect as it is. Awesome!
