### ISSUE TITLE
Little Mistake in your files

### ISSUE THREAD

**Issue by ayumihamsaki** [gauntface/simple-push-demo#37]
Hi,

First thanks for the code. I like the GA Event thing, just trying going through your code. I noticed a mistake. Your file: 

`/src/styles/main.scss`

In your index.html it says its pointing to:

`/src/styles/main.css`

I thought I'd let you know. Anyway, just going through your code and trying to learn more on push api. Not much information out there on the payload/encryption side (which is the only thing I need to learn now).

**Comment by oldergod** [comment]
Have a look here: https://github.com/gauntface/simple-push-demo/blob/master/gulp-tasks/styles.js#L55

The `main.css` file is generated by `gulp`.

**Comment by gauntface** [comment]
thanks all.

I'm going to have a look at simplifying everything. The number of people tripping up on this is giving me cause for concern and ultimately the sass is simple enough that it's not needed.

**Comment by gauntface** [comment]
I have it on the back burner to simplify the build process for this project. In the mean time I'm going to close this issue.
