### ISSUE TITLE
Any high level guide to complement this Repo?not an issue more of a suggestion) 

### ISSUE THREAD

**Issue by jasan-s** [gauntface/simple-push-demo#44]
Matt, THis seems to be the only Repo that i could find that uses FCM, all others seem to use GCM. IF you have time, please consider writing up a high level guide for this repo. Thanks

**Comment by gauntface** [comment]
It's on my TODO list, at the moment I'm having trouble getting it work anywhere other than via web crypto, but will do something ASAP.

**Comment by gauntface** [comment]
Apologies that this took so long, but here is the article: https://developers.google.com/web/updates/2016/07/web-push-interop-wins?hl=en
