### ISSUE TITLE
requestInfo.body needs single quotes when appended to curlCommand

### ISSUE THREAD

**Issue by agoode** [gauntface/simple-push-demo#45]
https://github.com/gauntface/simple-push-demo/blob/d053625b8dc98096482bbb63d8cc557be674ad92/src/scripts/app-controller.js#L237

You need single quotes since the JSON body contains double quotes already.

**Comment by gauntface** [comment]
Thanks for the issue, just took a PR that should fix this. Just needs some tests.

**Comment by gauntface** [comment]
Tests added - should be all fixed.
