### ISSUE TITLE
"Add Payload Text" version?

### ISSUE THREAD

**Issue by viniciusdepaula** [gauntface/simple-push-demo#48]
Where is the "Add Payload Text" version?
Thx a lot.

**Comment by oldergod** [comment]
You can only see it on supported browsers. The UI shoud look like this.

![image](https://cloud.githubusercontent.com/assets/1767669/16182082/11560cae-36dd-11e6-943d-0724ff6c7965.png)

**Comment by gauntface** [comment]
@viniciusdepaula what browser are you using?

**Comment by viniciusdepaula** [comment]
Hello,

Im using Version 51.0.2704.103 (64-bit) in OS X 10.10.5.

**Comment by gauntface** [comment]
Are you still not seeing the payload text? And this is chrome I presume

**Comment by gauntface** [comment]
Ignore chrome question, you already said :-P

This is the url you are using as well right? https://gauntface.github.io/simple-push-demo/

**Comment by viniciusdepaula** [comment]
Hey Matthew,

I can see the payload in https://gauntface.github.io/simple-push-demo/

Sorry for mistake it, im using the Demo Locally, and in that demo i missed the payload "how to do" guide. Could you help me?
<img width="1163" alt="image" src="https://cloud.githubusercontent.com/assets/11903599/16324971/ee14fa9c-398f-11e6-8ba7-df67723cd827.png">


Sorry for the inconvenience,

Thanks in advance!

Vinicius

**Comment by gauntface** [comment]
It looks like your running an older version of the local copy, are you definitely on this repo url and definitely up to date?

Try running:

    git fetch origin
    git pull origin master
    npm install
    gulp dev

If you are still not getting it, could you copy and paste the output of this:

    git remove -v

Cheers,
Matt

**Comment by oldergod** [comment]
If ever you are running this from a fork repo, you [need to sync it too](https://help.github.com/articles/syncing-a-fork/).

**Comment by viniciusdepaula** [comment]
Wow its worked!!

Thanks in advance!
