### ISSUE TITLE
Sequential notifications replace instead of adding

### ISSUE THREAD

**Issue by marcandrews** [gauntface/simple-push-demo#5]
It seems like sequential notifications are replaced instead of showing `You have X weather updates.` Any ideas on how to fix this?

**Comment by jpmedley** [comment]
ServiceWorkerRegistration.getNotifications() returns an array. Here's more about this: http://updates.html5rocks.com/2015/05/Notifying-you-of-notificiation-changes

**Comment by gauntface** [comment]
As Joe pointed out - this was to demonstrate that new API.

If you look at line 85 here (https://github.com/gauntface/simple-push-demo/blob/master/app/service-worker.js#L85) you'll see where I opt between using getNotifications vs just showing a new notification.
