### ISSUE TITLE
How would I modify your sample to send a notification only if tab is open?

### ISSUE THREAD

**Issue by borisreitman** [gauntface/simple-push-demo#6]
I don't want notifications when tab to my site is closed. It is confusing to the user. How can I check in the service worker that a tab is open? Or can I set the listener in the tab, instead of registering a service worker?

**Comment by jpmedley** [comment]
Use the ServiceWorkerGlobalScope.Clients interface. It would look something like this: https://github.com/GoogleChrome/samples/blob/gh-pages/push-messaging-and-notifications/service-worker.js

**Comment by gauntface** [comment]
I may be misunderstanding this but I read "I don't want notifications when tab to my site is closed" suggests you don't want push notifications for your site at all, but instead you want to be able to show notifications from your website.

As Joe pointed out, you can detect when a user has your site already open and focus that tab.
