### ISSUE TITLE
Demo fails on Samsung Android Browser

### ISSUE THREAD

**Issue by RichardMaher** [gauntface/simple-push-demo#66]
The Enable Push Notifications prompt/button is never enabled.

**Comment by gauntface** [comment]
Thanks for raising the issue. Just got my hands on a samsung device and it's failing because I was using ES2015. Will add a transpilation step back in the build process and it should fix the problem.

**Comment by gauntface** [comment]
Should be fixed now.

Please note that Samsung browser doesn't support payloads.

Thanks again for raising the issue.

**Comment by RichardMaher** [comment]
Thanks.
