### ISSUE TITLE
I am not posting issue

### ISSUE THREAD

**Issue by RahulMiglani** [gauntface/simple-push-demo#7]
Hi, 

Thanks for your great job!

Its working on my local using gulp. Can you please tell how I can use this for my website. I have uploaded all the files on my domain but its not working for me.

Can you please help me

**Comment by gauntface** [comment]
The best advice I can give is to follow the steps here: https://developers.google.com/web/updates/2015/03/push-notificatons-on-the-open-web

That walks through how to set up push notifications and is slightly simpler (This sample used Permissions API which is extremely new)
