### ISSUE TITLE
About crypto in this demo

### ISSUE THREAD

**Issue by felixsanz** [gauntface/simple-push-demo#72]
Can you please explain a bit why all that [ciphers, crypto, vapid] things? What is required for?

**Comment by gauntface** [comment]
The crypto side of things is required to encrypt the data that is sent with a push message. For example, when you send a push message with text typed in the demo, it's encrypted before it's sent to the push service.

You can learn more here: https://developers.google.com/web/updates/2016/03/web-push-encryption

VAPID is new and I've only just got around to clearing up a few issues. The article is currently being reviewed by a tech writer. Will update: #44 when it's published
