### ISSUE TITLE
Make the app available offline

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [gauntface/simple-push-demo#99]
Is web push notifications compatible with offline cache via service workers? Something like: if the browser is online, then everything proceeds as it normally would; if the browser is offline, the request is saved to IndexedDB, and each time the service worker script starts up it will attempt to "replay" those saved requests, (giving up after one day has passed).

Looks like an interesting use case.

**Comment by gauntface** [comment]
Sorry not sure what you mean.

Pushes are 99% of the time sent from the server, not the client, so there is no queuing from the client side ever needed. This demo sends messages from the client to a server that makes the web push request because it's a demo.
